services:
  web:
    build:
      context: . # Dockerfile 위치
      dockerfile: Dockerfile
    # platform: linux/arm64
    platform: linux/amd64
    ports:
      - 3000:3000
    env_file:
      - .env.production
