export enum ErrorCode {
  // auth
  AUTH_CODE_NOT_INCLUDED = 'AUTH_CODE_NOT_INCLUDED',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  UNAUTHORIZATION = 'UNAUTHORIZATION',
  CSRF_TOKEN_MISMATCH = 'CSRF_TOKEN_MISMATCH',
  CSRF_TOKEN_NOT_INCLUDED = 'CSRF_TOKEN_NOT_INCLUDED',

  // Google APIs
  YOUTUBE_SUBTITLE_DOWNLOAD_FAILED = 'YOUTUBE_SUBTITLE_DOWNLOAD_FAILED',
  YOUTUBE_VIDEO_GET_FAILED = 'YOUTUBE_VIDEO_GET_FAILED',
  YOUTUBE_VIDEO_NOT_FOUND = 'YOUTUBE_VIDEO_NOT_FOUND',
  OPENAI_TRANSCRIPTION_FAILED = 'OPENAI_TRANSCRIPTION_FAILED',

  // Fact Check
  FACT_CHECK_SESSION_NOT_FOUND = 'FACT_CHECK_SESSION_NOT_FOUND',
  CONTENT_TYPE_NOT_SUPPORTED = 'CONTENT_TYPE_NOT_SUPPORTED',
  FACTCHECK_SESSION_RESET = 'FACTCHECK_SESSION_RESET',
  EVIDENCE_RETRIEVAL_FAILED = 'EVIDENCE_RETRIEVAL_FAILED',
  CLAIMS_CREATE_FAILED = 'CLAIMS_CREATE_FAILED',
  CLAIM_VERIFICATIONS_CREATE_FAILED = 'CLAIM_VERIFICATIONS_CREATE_FAILED',
  CLAIM_VERIFICATIONS_READ_FAILED = 'CLAIM_VERIFICATIONS_READ_FAILED',
  CLAIM_VERIFICATIONS_DELETE_FAILED = 'CLAIM_VERIFICATIONS_DELETE_FAILED',
  FACT_CHECK_SESSIONS_READ_FAILED = 'FACT_CHECK_SESSIONS_READ_FAILED',
  FACT_CHECK_SESSIONS_DELETE_FAILED = 'FACT_CHECK_SESSIONS_DELETE_FAILED',
}
