export enum ErrorCode {
  // auth
  AUTH_CODE_NOT_INCLUDED = 'AUTH_CODE_NOT_INCLUDED',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  UNAUTHORIZATION = 'UNAUTHORIZATION',
  CSRF_TOKEN_MISMATCH = 'CSRF_TOKEN_MISMATCH',
  CSRF_TOKEN_NOT_INCLUDED = 'CSRF_TOKEN_NOT_INCLUDED',

  // Google APIs
  YOUTUBE_VIDEO_GET_FAILED = 'YOUTUBE_VIDEO_GET_FAILED',

  // Fact Check
  FACT_CHECK_SESSION_NOT_FOUND = 'FACT_CHECK_SESSION_NOT_FOUND',
  CONTENT_TYPE_NOT_SUPPORTED = 'CONTENT_TYPE_NOT_SUPPORTED',
}
