import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import AuthProvider from "./components/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html className="h-full" lang="en">
			{/* TODO: theme 적용 */}
			<body className={`${inter.className} h-full bg-[#F9FAFB]`}>
				<AuthProvider>
					<div className="flex flex-col h-full">
						<div className="top-0 right-0 left-0 fixed">
							<Header className="h-16" />
						</div>

						<div className="flex-1 mt-16">{children}</div>
					</div>
				</AuthProvider>
			</body>
		</html>
	);
}
