import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import AuthProvider from "./components/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html className="h-screen" lang="en">
			{/* TODO: theme 적용 */}
			<body className={`${inter.className} h-screen bg-[#F9FAFB]`}>
				<AuthProvider>
					<div className="flex flex-col h-full">
						<section className={`z-200 z- top-0 right-0 left-0 fixed h-16`}>
							<Header />
						</section>

						<section
							// className={`mt-16 h-[calc(100%-${Styles.header.height})]`}
							className="top-16 right-0 bottom-0 left-0 fixed overflow-y-auto"
						>
							{children}
						</section>
					</div>
				</AuthProvider>
			</body>
		</html>
	);
}
