export enum ErrorCode {
  // auth
  AUTH_CODE_NOT_INCLUDED = 'AUTH_CODE_NOT_INCLUDED',
  UNAUTHORIZATION = 'UNAUTHORIZATION',
  CSRF_TOKEN_MISMATCH = 'CSRF_TOKEN_MISMATCH',
  CSRF_TOKEN_NOT_INCLUDED = 'CSRF_TOKEN_NOT_INCLUDED',

  // Google APIs
  YOUTUBE_VIDEO_GET_FAILED = 'YOUTUBE_VIDEO_GET_FAILED',
}
