export enum ErrorCode {
	// auth
	AUTH_CODE_NOT_INCLUDED = "AUTH_CODE_NOT_INCLUDED",
	ACCESS_TOKEN_GENERATION_FAILED = "ACCESS_TOKEN_GENERATION_FAILED",
	UNAUTHORIZATION = "UNAUTHORIZATION",
	CSRF_TOKEN_MISMATCH = "CSRF_TOKEN_MISMATCH",
	CSRF_TOKEN_NOT_INCLUDED = "CSRF_TOKEN_NOT_INCLUDED",
	// Google APIs

	// Fact Check
	INVALID_FACT_CHECKER_PIPELINE_ORDER = "INVALID_FACT_CHECKER_PIPELINE_ORDER",
}
